<!DOCTYPE html>
<html lang="es">
    <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sistema de Activo Fijo | Principal</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
    <?php Tag::css('bootstrap/bootstrap'); ?>
    <!-- Font Awesome -->
    <?php Tag::css('font-awesome.min'); ?>
    <!-- Font Awesome -->
    <?php Tag::css('kumbia/font-awesome.min'); ?>
    <!-- Ionicons -->
    <?php Tag::css('ionicons/ionicons.min'); ?>
    <!-- iCheck -->
    <?php Tag::css('plugins/iCheck/square/blue'); ?>
    <!--theme -->
    <?php Tag::css('skins/_all-skins.min'); ?>
    <!-- Select2 -->
    <?php Tag::css('select2/dist/css/select2.min'); ?>
    <?php //Tag::css('style'); ?>
    <?php //Tag::css('backend/base'); ?>
    <?php Tag::css('backend/style'); ?>
    <?php //Tag::css('backend/themes/'.SKIN.'/'.SKIN); ?>
    <?php Tag::css('file-upload'); ?>
    <!-- Theme style -->
    <?php Tag::css('AdminLTE'); ?>
    <!-- Incluir CSS -->
    <?php Tag::css('datatable/datatable.min'); ?>
    <?php echo Html::includeCss(); ?>

    <!-- jQuery 3 -->
    <?php echo Tag::js('jquery/jquery').PHP_EOL; ?>
    <script type="text/javascript">
      function DwTitle(title) { if($(document).attr('title') != title) { $(document).attr('title', title); } }
    </script>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
    <body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>S</b>AF</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><?php echo DwHtml::img("upload/empresa/".APP_CLIENT_LOGO, APP_NAME, array('style'=>'')); ?></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <?php echo DwHtml::img("boxed-bg.png","Usuario", array('class'=>'img-circle','style'=>'width:20px'), '' , FALSE);?>
              <span class="hidden-xs"><?php echo Session::get("nombre") ." ".Session::get("apellido") ?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <?php echo DwHtml::img("boxed-bg.png","Usuario", array('class'=>'img-circle'), '' , FALSE);?>

                <p>
                  <?php echo Session::get("nombre") ." ".Session::get("apellido") ?>
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Perfil</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Cerrar Sesión</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <?php echo DwHtml::img("boxed-bg.png","Usuario", array('class'=>'img-circle'), '' , FALSE);?>
        </div>
        <div class="pull-left info">
          <p><?php echo Session::get("nombre") ." ".Session::get("apellido") ?></p>
          <?php echo DwHtml::link('sistema/login/salir', 'Online', array('class'=>'no-load'), 'fa fa-circle text-success', FALSE); ?>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <?php DwMenu::load(Menu::BACKEND, Session::get('perfil_id')); ?>

       <?php echo DwMenu::desktop(); ?>
       
      </section>
    <!-- /.sidebar -->
    </aside>
       <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
            <div id="dw-console" class="container"></div>
            <div id="dw-shell-content" class="container-fluid">
                <noscript><h5 style="text-align: center;">¡Tu navegador no soporta Javascript!.. Activa el uso de Javascript en tu navegador.</h5><meta http-equiv="refresh" content="1; URL=<?php echo PUBLIC_PATH; ?>sistema/login/salir/no-script/" /></noscript>
                <?php View::content(); ?>
            </div>
    </section>
    </div>

    <?php View::partial('backend/footer'); ?>

        <div id="dw-loading-content" class="alpha60"></div>
        <div id="dw-spinner" class="preview dw-corner-all dw-shadow-dark"></div>

    <!-- jQuery UI 1.11.4 -->
    <?php echo Tag::js('jquery-ui/jquery-ui.min').PHP_EOL; ?>
    <!-- Bootstrap 3.3.7 -->
    <?php echo Tag::js('bootstrap/bootstrap.min').PHP_EOL; ?>
    <!-- AdminLTE App -->
    <?php echo Tag::js('adminlte.min').PHP_EOL; ?>

    <?php echo Tag::js('jquery/jquery1.8.min').PHP_EOL; ?>
    <?php echo Tag::js('bootstrap/bootstrap-datepicker').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.keyfilter').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.dwgrid').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.dwload').PHP_EOL; ?>
    <?php echo Tag::js('vendors/jsspin.min').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.spin').PHP_EOL; ?>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <?php echo Tag::js('vendors/html5').PHP_EOL; ?>
    <![endif]-->
    <?php echo Tag::js('utils/var').PHP_EOL; ?>
    <?php echo Tag::js('utils/validador').PHP_EOL; ?>


    <?php echo Tag::js("bootstrap/bootstrap2.3"); ?>
    <script type="text/javascript">
        
        $(function() {
            $("[rel=tooltip]").tooltip();
        });
    </script>

    <!-- Select2 -->
    <?php echo Tag::js("select2/dist/js/select2.full.min") ?>
    <!-- InputMask -->
    <?php echo Tag::js("plugins/input-mask/jquery.inputmask") ?>
    <?php echo Tag::js("plugins/input-mask/jquery.inputmask.date.extensions") ?>
    <?php echo Tag::js("plugins/input-mask/jquery.inputmask.extensions") ?>
    <!-- bootstrap color picker -->
    <?php echo Tag::js("bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min") ?>
    <!-- bootstrap time picker -->
    <?php echo Tag::js("plugins/timepicker/bootstrap-timepicker.min") ?>
    <!-- iCheck 1.0.1 -->
    <?php echo Tag::js("plugins/iCheck/icheck.min") ?>

    <?php echo DwDialog::alert('Se ha producido un error en la validación del formulario.', 'subtext: Verifica los datos e intenta nuevamente.', 'title: Formulario incorrecto', 'name: errorForm'); ?>
    <?php if(PRODUCTION) { ?>
    <?php echo DwDialog::alert('Se ha generado la siguiente excepción: <br /><span id="dw-error-ajax"></span>.', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
    <?php } else { ?>
    <?php echo DwDialog::alert('Se ha generado la siguiente excepción: <br /><span id="dw-error-ajax"></span>.<br /><span id="dw-info-error-ajax"></span>', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
    <?php } ?>
    <?php echo DwDialog::alert('Usted no posee los permisos necesarios para realizar esta acción.', 'title: Acceso denegado', 'name: accessControl'); ?>

    <?php echo Tag::js("jquery3.5/jquery3.5") ?>
    <?php echo Tag::js("plugins/datatable/datatable") ?>
    
    </body>
</html>
