<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sistema Oftalmologico | Inicio de Sesion</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta charset="<?php echo APP_CHARSET; ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow" />
    <!-- Bootstrap 3.3.7 -->
    <?php Tag::css('bootstrap/bootstrap'); ?>
    <!-- Font Awesome -->
    <?php Tag::css('font-awesome.min'); ?>
    <!-- Ionicons -->
    <?php Tag::css('ionicons/ionicons.min'); ?>
    <!-- Theme style -->
    <?php Tag::css('AdminLTE.min'); ?>
    <!-- iCheck -->
    <?php Tag::css('plugins/iCheck/square/blue'); ?>
    <!-- Incluir CSS -->
    
    <?php echo Html::includeCss(); ?>
    
    <style>
    .example-modal .modal {
      position: relative;
      top: auto;
      bottom: auto;
      right: auto;
      left: auto;
      display: block;
      z-index: 1;
    }

    .example-modal .modal {
      background: transparent !important;
    }
  </style>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
    
    <!-- jQuery 3 -->
    <?php echo Tag::js('jquery/jquery').PHP_EOL; ?>
    <!-- jQuery UI 1.11.4 -->
    <?php echo Tag::js('jquery-ui/jquery-ui.min').PHP_EOL; ?>
    <!-- Bootstrap 3.3.7 -->
    <?php echo Tag::js('bootstrap/bootstrap.min').PHP_EOL; ?>
    <!-- AdminLTE App -->
    <?php echo Tag::js('adminlte.min').PHP_EOL; ?>
    

  <!-- Google Font -->
  <?php if(!APP_LOCAL) { ?>
            <link href="http://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" type="text/css">
    <?php } ?>
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Sistema de</b> Activo Fijo</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg"><?php //echo DwHtml::img("upload/empresa/".APP_CLIENT_LOGO, APP_CLIENT, array('style'=>'height: 50px;'));?>INICIAR SESIÓN</p>
    <?php View::content(); ?>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<div id="dw-loading-content" class="alpha60"></div>
        <div id="dw-spinner" class="preview dw-corner-all dw-shadow-dark"></div>

        <script type="text/javascript">
            $(function () {
                jQuery.support.placeholder = false;
                test = document.createElement('input');
                if('placeholder' in test) jQuery.support.placeholder = true;
                if (!$.support.placeholder) {
                    $('.field').find ('label').show();
                }
            });
        </script>
<!-- Jquery 1.8 -->
<?php echo Tag::js('jquery/jquery1.8.min').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.kumbiaphp').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.keyfilter').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.dwload').PHP_EOL; ?>
<?php echo Tag::js('vendors/jsspin.min').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.spin').PHP_EOL; ?>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<?php echo Tag::js('vendors/html5').PHP_EOL; ?>
<![endif]-->
<?php echo Tag::js('utils/var').PHP_EOL; ?>

<?php echo DwDialog::alert('Se ha generado la siguiente excepción: <br /><span id="dw-error-ajax"></span>.', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php echo DwDialog::alert('Se ha producido un error en la validación del formulario.', 'subtext: Verifica los datos e intenta nuevamente.', 'title: Formulario incorrecto', 'name: errorForm'); ?>

</body>
</html>
