<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title); ?>

    <table class="table table-bordered table-hover table-striped table-condensed">
        <thead>
            <tr>
                <th class="no-responsive dw-text-middle" style="width: 15px;">NUM</th>
                <th class="no-responsive dw-text-middle">FECHA</th>
                <th class="no-responsive dw-text-middle">TIPO</th>
                <th class="no-responsive dw-text-middle">USUARIO</th>
                <th class="no-responsive dw-text-middle">IP</th>
                <th class="no-responsive dw-text-center">DESCRIPCION</th>
            </tr>
        </thead>
        <tbody>
           
        </tbody>

    </table>

</div>